base/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('ticket_verified/', ticket_verified, name='ticket_verified'),
    path('user_staff/', user_staff, name='user_staff'),
    path('user_controller/', user_controller, name='user_controller'),
    path('modify_user_role_staff/<int:user_id>/', modify_user_role_staff, name='modify_user_role_staff'),
    path('modify_user_role_controller/<int:user_id>/', modify_user_role_controller, name='modify_user_role_controller'),

    path('controller/', controller, name='controller'),
    path('controller_ticket/', controller_ticket, name='controller_ticket'),

    path('staff/', staff, name='staff'),
    path('repair_request_details_staff/<int:event_id>/', repair_request_details_staff, name='repair_request_details_staff'),
    path('complete_request/<int:request_id>/', complete_request, name='complete_request'),

    path('repair/', repair, name="repair"),
    path('ticket_logs/', ticket_logs, name="ticket_logs"),
    # department
    path('repair-request/', repair_request, name="repair_request"),
    path('repair_request_details/<int:event_id>/', repair_request_details, name='repair_request_details'),
    path('asign/<int:pk>/', asign, name='asign'),
    path('forasignstaff/<int:pk>/', forasignstaff, name='forasignstaff'),
    path('forasignstaffstatus/<int:pk>/', forasignstaffstatus, name='forasignstaffstatus'),
    path('repair_request_again/', repair_request_again, name="repair_request_again"),

    path('login/', user_login, name='login'),
    path('logout/', user_logout, name="logout"),

    path('get-offices/', get_offices_by_department, name='get_offices_by_department'),
    path('add_user/', add_user, name='add_user'),

    path('verify-request/<int:request_id>/', verify_request, name='verify_request'),

    

]

ticketing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("base.urls")),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User, Group
import uuid
from django.db.models import Count

# Create your models here.
    
class Department(models.Model):
    name = models.CharField(max_length=50, blank=True)
    def __str__(self):
        return self.name
    
class Office(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True, unique=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.name
    
class KindOfEquipment(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
    
class RepairDescription(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name
    
class RepairRequest(models.Model):
    STATUS_CHOICES = (
        ('ongoing', 'Ongoing'),
        ('complete', 'Complete'),
    )
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    office = models.ForeignKey(Office, on_delete=models.CASCADE)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    description_staff = models.ForeignKey(RepairDescription, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=True, null=True)
    equip_type = models.ForeignKey(KindOfEquipment, on_delete=models.CASCADE, null=True)
    description = models.CharField(max_length=600, blank=True, null=True)
    date = models.DateTimeField(auto_now_add=True, null=True)
    staff = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    property_num = models.IntegerField(unique=True, null=True, blank=True)
    serial_num = models.IntegerField(unique=True, null=True, blank=True)
    kind_of_work = models.CharField(max_length=500, blank=True, null=True)
    complete = models.BooleanField(default=False)
    verified = models.BooleanField(default=False)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')

    staff_id = 1


    def __str__(self):
         return f"{self.office}"
    
    def save(self, *args, **kwargs):
        if self.first_name:
            self.first_name = self.first_name.upper()
        if self.last_name:
            self.last_name = self.last_name.upper()
        super().save(*args, **kwargs)
    #set data to upper()
    
class TicketLogs(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    logs = models.CharField(max_length=150, null=True, blank=True)
    date = models.DateTimeField(auto_now_add=True, null=True)

templates/repair_request/repair_request.html
{% load static %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <body class="hold-transition login-page">
    <div class="login-box">
      <!-- /.login-logo -->
      <div class="card card-outline card-success">
        <div class="card-header text-center">
          <a href="{% url 'login' %}" class="h1"><b>IT</b>Help Desk</a><br>
        </div>
        <!-- <div class="text-center"><h4><i>(HOPSS)</i></h4></div> -->
        <form method="post" id="repair-request-form">
            {% csrf_token %}
            {{ hopps_form.office.errors }}
            <div class="card-body">
                {{ hopps_form }} <br>
                <div class="row">
                    <div class="col-8">
                        <div class="icheck-success">
                            <label for="id_remember">
                                <p class="mb-1">
                                    <a href="{% url 'login' %}" class="text-primary">Back</a>
                                </p>
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-success btn-block">Submit</button>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
        </form>
        
        <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
        <script>
            $(document).ready(function () {
                function updateOfficeOptions() {
                    var departmentId = $('#id_department').val();
                    var officeSelect = $('#id_office');
        
                    // Clear current options
                    officeSelect.empty();
        
                    $.ajax({
                        url: '{% url "get_offices_by_department" %}',
                        type: 'GET',
                        data: { 'department_id': departmentId },
                        success: function (data) {
                            $.each(data.offices, function (key, value) {
                                officeSelect.append($('<option>').text(value).attr('value', key));
                            });
                        },
                        error: function () {
                            console.error('Error fetching offices.');
                        }
                    });
                }
        
                $('#id_department').change(updateOfficeOptions);
                updateOfficeOptions();
            });
        </script>
        
        <!-- /.card-body -->
      </div>

      <!-- /.card -->
    </div>
    <!-- /.login-box -->

templates/repair_request/repair_request_again.html
{% load static %}
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <body class="hold-transition login-page">
    <div class="login-box">
      <!-- /.login-logo -->
      <div class="card card-outline card-success">
        <div class="card-header text-center">
          <a href="{% url 'login' %}" class="h1"><b>IT</b>Help Desk</a><br>
        </div>
        <div class="text-center"><h4><i>(HOPSS)</i></h4></div>
        <form method="post">
          {% csrf_token %}
          <div class="card-body">
            {% if messages %}
            <div class="alert" role="alert">
              {% for message in messages %}
              <h5 class="text-success"><i>{{ message }}</i></h5 class="text-success">
              {% endfor %}
            </div>
            {% endif %} <br>
            <div class="row">
              <div class="col-6">
                <div class="icheck-success">
                
                  <label for="remember">

                  </label>
                </div>
              </div>
              <!-- /.col -->
              <div class="col-6">
                <a href="{% url 'repair_request' %}" class="btn btn-secondary btn-block">Request Again</a>
              </div>
              <!-- /.col -->
            </div>
          </div>
        </form>
        <!-- /.card-body -->
      </div>

      <!-- /.card -->
    </div>
    <!-- /.login-box -->

templates/repair_request/repair_request_details.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{{ hopps3.office }}{% endblock title %}</title>
  
  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__wobble" src="{% static 'dist/img/AdminLTELogo.png' %}" alt="AdminLTELogo" height="60" width="60">
  </div>

{% include 'nav.html' %}
{% include 'side.html' %}
<style>
  .content .row {
    display: flex;
    justify-content: center;
  }
</style>
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        {% block chw %}
        <h5>{{ hopps3.office }}</span>
        {% endblock chw %}
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-4">
              <!-- general form elements -->
              <div class="card card-success">
                <div class="card-header">
                <h5>RR{{ hopss3.date|date:"Y" }}-000{{ hopps3.id }}</h5>
                </div>
                <div class="text-center"></div>
                <!-- /.card-header -->
                <!-- form start -->
                <form>
                  <div class="card-body">
                    <!-- <div class="form-group">
                      <label for="exampleInputEmail1">Office</label>
                      <input type="text" class="form-control" placeholder="Office" value="{{ hopps3.office }}" readonly>
                    </div> -->
                    <div class="form-group">
                      <label for="exampleInputPassword1">Requested By:</label>
                      <input type="text" class="form-control" placeholder="Password" value="{{ hopps3.first_name }}" readonly>
                    </div>
               
                    <div class="form-group">
                        <label for="exampleInputPassword1">Problem Description</label>
                        <textarea class="form-control" id="description" placeholder="Description" readonly>{{ hopps3.description }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Assign Staff</label>
                        <!-- <input type="text" class="form-control" placeholder="None" value="{{ hopps3.staff.get_full_name }}" readonly> -->
                        <input type="text" class="form-control" placeholder="None" value="{{ hopps3.staff }}" readonly>
                    </div>
                  </div>
                </form>
              </div>
  
            </div>
          </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
<!-- {% include 'footer.html' %} -->
</div>
<!-- ./wrapper -->
{% include 'scripts.html' %}
</body>
</html>

templates/repair_request/repair_request_update.html
{% extends 'base.html' %}
{% block title %}Crop{% endblock title %}
{% block content %}
<section class="content">
    <div class="container-fluid">
        <div class="row"> 
            <div class="container">
                <div class="row mt-5">
                    <div class="col-md-6 offset-md-3">
                        <div class="border bg-white p-3">
                        
                            <hr>
                            <form method="POST">
                                {% csrf_token %}
                                <div class="col-12 mb-4">{{ form }}</div>
                                <a href="{% url 'controller_ticket' %}" class="btn btn-secondary">Back</a>
                                <input type="submit" value="Assign" class="btn btn-info">
                            </form>                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
        
{% endblock content %}

templates/repair_request/repair_request_update_staff.html
{% extends 'staff/staff.html' %}
{% block title %}Crop{% endblock title %}
{% block content %}
<section class="content">
    <div class="container-fluid">
        <div class="row"> 
            <div class="container">
                <div class="row mt-5">
                    <div class="col-md-6 offset-md-3">
                        <div class="border bg-white p-3">
                        
                            <hr>
                            <form method="POST">
                                {% csrf_token %}
                                <div class="col-12 mb-4">{{ form }}</div>
                                <a href="{% url 'staff' %}" class="btn btn-secondary">Back</a>
                                <input type="submit" value="Assign" class="btn btn-info">
                            </form>                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
        
{% endblock content %}

templates/repair_request/repair_status.html
{% extends 'staff/staff.html' %}
{% block title %}Crop{% endblock title %}
{% block content %}
<section class="content">
    <div class="container-fluid">
        <div class="row"> 
            <div class="container">
                <div class="row mt-5">
                    <div class="col-md-6 offset-md-3">
                        <div class="border bg-white p-3">
                        
                            <hr>
                            <form method="POST">
                                {% csrf_token %}
                                <div class="col-12 mb-4">{{ form }}</div>
                                <a href="{% url 'staff' %}" class="btn btn-secondary">Back</a>
                                <input type="submit" value="Save" class="btn btn-info">
                            </form>                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
        
{% endblock content %}